"""initial

Revision ID: 85272be0c3ba
Revises: 
Create Date: 2025-07-31 20:43:14.204886

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '85272be0c3ba'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='False', nullable=False),
    sa.Column('level', sa.Integer(), server_default='100', nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.CheckConstraint('length(name) > 0', name='name_length_check'),
    sa.CheckConstraint('length(slug) > 0', name='slug_length_check'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'level', name='uq_categories_name_level'),
    sa.UniqueConstraint('slug'),
    sa.UniqueConstraint('slug', name='uq_categories_slug')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('categories')
    # ### end Alembic commands ###
